# Generated by Django 5.0.4 on 2024-04-19 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro', 'Outro')], max_length=25)),
                ('genero', models.CharField(max_length=256)),
                ('data_nascimento', models.DateField()),
                ('rg', models.CharField(max_length=9)),
                ('cpf', models.CharField(max_length=11)),
                ('status_dependencia', models.CharField(choices=[('Independente', 'Independente'), ('Dependente', 'Dependente')], max_length=20)),
                ('nome_responsavel', models.CharField(blank=True, max_length=256, null=True)),
                ('rg_responsavel', models.CharField(blank=True, max_length=9, null=True)),
                ('cpf_responsavel', models.CharField(blank=True, max_length=11, null=True)),
                ('telefone', models.CharField(max_length=14)),
                ('cep', models.CharField(max_length=8)),
                ('endereco', models.TextField()),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tamanho', models.DecimalField(decimal_places=2, max_digits=3)),
                ('alergia', models.BooleanField()),
                ('doenca', models.BooleanField()),
                ('fuma', models.BooleanField()),
                ('bebe', models.BooleanField()),
                ('uso_drogas', models.BooleanField()),
                ('observacoes', models.TextField(null=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_documento', models.CharField(max_length=256)),
                ('descricao', models.TextField(null=True)),
                ('file_documento', models.FileField(upload_to='exames/')),
                ('prontuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='paciente.prontuario')),
            ],
        ),
    ]
