# Generated by Django 5.0.4 on 2024-04-19 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentos',
            options={'verbose_name_plural': 'Documentos'},
        ),
    ]
