# Generated by Django 5.0.4 on 2024-04-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
