# Generated by Django 5.0.4 on 2024-04-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cpf_responsavel',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rg_responsavel',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
