# Generated by Django 5.0.4 on 2024-04-19 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
        ('medico', '0001_initial'),
        ('paciente', '0002_alter_documentos_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cartao', models.CharField(max_length=256)),
                ('cvc', models.CharField(max_length=3)),
                ('data_vencimento', models.CharField(max_length=7)),
                ('bandeira_cartao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clinica.bandeiracartao')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
            ],
            options={
                'verbose_name_plural': 'CadCartao',
            },
        ),
        migrations.CreateModel(
            name='CadConvenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_carteirinha', models.CharField(max_length=256)),
                ('convenio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clinica.convenio')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
                ('plano_convenio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clinica.planoconvenio')),
            ],
            options={
                'verbose_name_plural': 'CadConvenio',
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_consulta', models.CharField(choices=[('Presencial', 'Presencial'), ('Remoto', 'Remoto')], max_length=256)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('status_consulta', models.CharField(choices=[('Concluida', 'Concluida'), ('Cancelada', 'Cancelada'), ('Agendada', 'Agendada'), ('Em andamento', 'Em andamento')], max_length=256)),
                ('especialidade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medico.especialidade')),
                ('medico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medico.medico')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateField()),
                ('forma_pagamento', models.CharField(choices=[('Convenio', 'Convenio'), ('Cartao', 'Cartao'), ('Pix', 'Pix'), ('Pagar no dia', 'Pagar no dia')], max_length=256)),
                ('status_pagamento', models.CharField(choices=[('Pago', 'Pago'), ('Aguardando pagamento', 'Aguardando pagamento'), ('Cancelado', 'Cancelado'), ('Aguardando reembolso', 'Aguardando reembolso'), ('Reembolsado', 'Reembolsado')], max_length=256)),
                ('data_pagamento', models.CharField(blank=True, max_length=256, null=True)),
                ('cartao', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paciente.cadcartao')),
                ('convenio', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paciente.cadconvenio')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medico.medico')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
                ('pix', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinica.pix')),
                ('tratamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.tratamento')),
            ],
        ),
        migrations.AddConstraint(
            model_name='cadconvenio',
            constraint=models.UniqueConstraint(fields=('convenio', 'plano_convenio'), name='unique_convenio_plano_convenio'),
        ),
    ]
