# Generated by Django 5.0.4 on 2024-05-18 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_alter_encaminhamento_file_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=45)),
                ('num_boleto', models.CharField(max_length=13)),
            ],
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='boleto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.boleto'),
        ),
    ]
