# Generated by Django 5.0.4 on 2024-04-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_alter_paciente_cpf_responsavel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='status_dependencia',
            field=models.CharField(max_length=20),
        ),
    ]
