# Generated by Django 5.0.4 on 2024-05-18 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_boleto_alter_pagamento_boleto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boleto',
            old_name='num_boleto',
            new_name='cod_barras',
        ),
    ]
