CREATE TABLE Funcionario (
	ID_Funcionario INT PRIMARY KEY IDENTITY(1,1),
	Nome VARCHAR(50) NOT NULL,
	RG VARCHAR(9) NOT NULL,
	CPF VARCHAR(11) NOT NULL,
	Data_Nascimento DATE NOT NULL,
	Naturalidade VARCHAR(50) NOT NULL,
	ID_Sexo INT NOT NULL,
	Genero VARCHAR(50) NOT NULL,
	ID_Funcao INT NOT NULL,
	Telefone VARCHAR(11) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	CEP VARCHAR(8) NOT NULL,
	Endereco VARCHAR(MAX) NOT NULL,
	N_Endereco INT NOT NULL,
	Complemento VARCHAR(MAX),
	Data_de_Contratação DATETIME NOT NULL,
	Data_de_Rescisão DATETIME NOT NULL
)

ALTER TABLE Funcionario 
ADD CONSTRAINT fk_FUNCAO FOREIGN KEY (ID_Funcao) REFERENCES Cargo_Funcionario(ID_Cargo_Funcionario)
ALTER TABLE Funcionario 
ADD CONSTRAINT fk_SEXO FOREIGN KEY (ID_Sexo) REFERENCES Sexo(ID_Sexo)