CREATE TABLE Responsavel(
	ID_Responsavel INT PRIMARY KEY IDENTITY(1,1),
	Nome VARCHAR(50) NOT NULL,
	RG VARCHAR(9) NOT NULL,
	CPF VARCHAR(11) NOT NULL,
	ID_Sexo INT NOT NULL,
	Genero VARCHAR(50) NOT NULL,
	ID_Paciente INT NOT NULL
)

ALTER TABLE Responsavel
ADD CONSTRAINT fk_Responsavel FOREIGN KEY(ID_Paciente) REFERENCES Paciente(ID_Paciente)
ALTER TABLE Responsavel
ADD CONSTRAINT fk_SEXO_Resp FOREIGN KEY (ID_Sexo) REFERENCES Sexo(ID_Sexo)